// This file is autogenerated, DO NOT EDIT
// connector/apis/update-connector-error-api.asciidoc:80

[source, python]
----
resp = client.perform_request(
    "PUT",
    "/_connector/my-connector/_error",
    headers={"Content-Type": "application/json"},
    body={
        "error": "Houston, we have a problem!"
    },
)
print(resp)
----
